### PR TITLE
linux instructions added

### PR DESCRIPTION
**Pull request by rickytrevor**

### CODE REVIEW

**Comment by PotatoOfDoom** [comment]
Thank you for your contribution. I'll have to revise the description in the future anyway, but your guide seems like a good start.

**Comment by rickytrevor** [comment]
maybe it would be better if I were to create an install script to make it dead easy to setup

**Comment by JacekJagosz** [comment]
On Linux the path to Steam is not always the same. Also if you have a game installed using Lutris or Heroic that script won't work. I don't think it is that necessary, but maybe I haven't thought of a simple way to do it.

**Comment by rickytrevor** [comment]
I was thinking about that in this exact moment...I have to see where each launcher stores it's prefixes and ask the user what launcher they are using

**Pull request merged**
